# Generated by Django 5.1.5 on 2025-02-01 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='tx_ref',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
