# Generated by Django 5.0.4 on 2024-05-13 06:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_deadline_student_courses'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Deadline',
        ),
        migrations.RemoveField(
            model_name='student',
            name='courses',
        ),
    ]
