# Generated by Django 5.0.4 on 2024-05-13 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='course_code',
            field=models.CharField(max_length=10, primary_key=True, serialize=False),
        ),
    ]
