# Generated by Django 5.0.4 on 2024-04-08 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_remove_course_prerequisites_course_prerequisites'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='schedule_id',
            new_name='schedule',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='id',
            new_name='student_id',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='name',
            new_name='student_name',
        ),
        migrations.RenameField(
            model_name='studentregistration',
            old_name='id',
            new_name='registration_id',
        ),
    ]
